### ISSUE TITLE
Adjustment for having virtualenv created successfully on windows

### ISSUE THREAD

**Issue by dom-devel** [Kwpolska/ansible-nginx-uwsgi#4]
Putting this help here for anyone trying to get this up and running on Windows.

The vagrant role `setup_venv_app`, will fail here because something something Windows  + Vagrant.

Here's the [full link](https://github.com/gratipay/gratipay.com/issues/2327).

It can be solved in this case by switching main.yml in `setup_venv_app` as follows to include `--always-copy`

```
---
 ...
- name: Create a virtual environment
  command: "{{ virtualenv_cmd }} '{{ base_dir }}' --always-copy"
```

Here's the error for those Googling:

```
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 9, in <module>
    load_entry_point('virtualenv==15.0.1', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 942, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 1400, in install_python
    os.symlink(py_executable_base, full_pth)
OSError: [Errno 71] Protocol error: 'python3' -> '/srv/www/test/bin/python'
```

**Comment by Kwpolska** [comment]
I won’t default to `--always-copy` because (a) it wastes disk space, (b) it breaks on my Fedora box:

```pytb
[kwpolska@kw-nayru /tmp]% virtualenv-3.6 foo2 --always-copy
Using base prefix '/usr'
Cannot find file lib (bad symlink)
New python executable in /tmp/foo2/bin/python3
Also creating executable in /tmp/foo2/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /tmp/foo2/bin/python3 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/tmp/foo2/lib64/python3.6/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/tmp/foo2/lib64/python3.6/random.py", line 42, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ModuleNotFoundError: No module named 'math'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv-3.6", line 11, in <module>
    load_entry_point('virtualenv==16.0.0', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python3.6/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/lib/python3.6/site-packages/virtualenv.py", line 947, in create_environment
    download=download,
  File "/usr/lib/python3.6/site-packages/virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3.6/site-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /tmp/foo2/bin/python3 - setuptools pip wheel failed with error code 1
```

Also, I had no issues with Vagrant on Windows back in March/April 2017 when I did testing for this guide on Windows.

(1) what image are you using? (2) are you doing anything with `/vagrant` or other shared directories? This could be an explanation.

**Comment by Kwpolska** [comment]
Reproduced by trying to create virtualenv in a shared directory. Don’t do this. Added a note in the README file.

**Comment by dom-devel** [comment]
That's a good catch, I hadn't quite spotted that myself. 

The windows setup is a little weird, I have a ubuntu vagrant box which runs Ansible (no Windows support), then I have secondary vagrant machines that I run against.

I thought the easiest way of working, would be to symlink the `/srv/www` directory to a Windows folder, so I could directly alter the code without having to upload through git or another manner to remote machine, but I will freely admit I'm a bit of a novice to this sort of thing.

**Comment by Kwpolska** [comment]
You will need to remote in to reload uwsgi after changing ~~settings~~ the code anyway. Git will let you revert to an older version easily if you mess something up.
